---
- name: Reset lab to default configlet profile
  hosts: cvp1

  vars_files:
    - ../vars/CVP_model.yml
  tasks:
    - name: Upload dummy configlet
      arista.cvp.cv_configlet_v3:
        configlets: "{{ CVP_CONFIGLETS }}"
    - name: Build default container topology
      arista.cvp.cv_container_v3:
        topology: "{{ CONTAINERS_DUMMY }}"
        apply_mode: strict
    - name: Build default container topology
      arista.cvp.cv_container_v3:
        topology: "{{ CONTAINERS_DEFAULT }}"
        apply_mode: strict
    - name: Apply configlets for default config
      arista.cvp.cv_device_v3:
        devices: "{{ CVP_DEVICES_DEFAULT }}"
        state: present
        apply_mode: strict
      register: APPLY_RESULTS
    - name: Validate configlets
      arista.cvp.cv_validate_v3:
        validate_mode: ignore
        devices: "{{ VALIDATE_DEVICES }}"
    - name: Run change control without interaction
      arista.cvp.cv_task_v3:
        tasks: "{{ APPLY_RESULTS.taskIds }}"
