---
global_settings:
  isis_instance: Osiris
  mtu: 1550
devices:
  leaf1:
    isis:
      area: 49.0001
      id: 0000.0001.0001
      type: level-1
    interfaces:
      loopbacks:
        loopback0: 192.168.101.1
      p2p:
        - Ethernet1
        - Ethernet2
  leaf2:
    isis:
      area: 49.0001
      id: 0000.0001.0002
      type: level-1-2
    interfaces:
      loopbacks:
        loopback0: 192.168.101.2
      p2p:
        - Ethernet3
        - Ethernet1
        - Ethernet2
  leaf3:
    isis:
      area: 49.0003
      id: 0000.0001.0003
      type: level-1-2
    interfaces:
      loopbacks:
        loopback0: 192.168.101.3
      p2p:
        - Ethernet4
        - Ethernet1
        - Ethernet2
  leaf4:
    isis:
      area: 49.0003
      id: 0000.0001.0004
      type: level-1-2
    interfaces:
      loopbacks:
        loopback0: 192.168.101.4
      p2p:
        - Ethernet1
        - Ethernet2
        - Ethernet5
        - Ethernet6
  spine1:
    isis:
      area: 49.0002
      id: 0000.0002.0001
      type: level-1-2
    interfaces:
      loopbacks:
        loopback0: 192.168.101.101
      p2p:
        - Ethernet4
        - Ethernet1
  spine2:
    isis:
      area: 49.0002
      id: 0000.0002.0002
      type: level-1-2
    interfaces:
      loopbacks:
        loopback0: 192.168.101.102
      p2p:
        - Ethernet1
        - Ethernet5
  spine3:
    isis:
      area: 49.0004
      id: 0000.0002.0003
      type: level-1-2
    interfaces:
      loopbacks:
        loopback0: 192.168.101.103
      p2p:
        - Ethernet6
        - Ethernet1
        - Ethernet7
  spine4:
    isis:
      area: 49.0004
      id: 0000.0002.0004
      type: level-1-2
    interfaces:
      loopbacks:
        loopback0: 192.168.101.104
      p2p:
        - Ethernet6
        - Ethernet1
        - Ethernet8
  borderleaf1:
    isis:
      area: 49.0004
      id: 0000.0003.0001
      type: level-1
    interfaces:
      loopbacks:
        loopback0: 192.168.101.121
      p2p:
        - Ethernet1
        - Ethernet5
  borderleaf2:
    isis:
      area: 49.0004
      id: 0000.0003.0002
      type: level-1
    interfaces:
      loopbacks:
        loopback0: 192.168.101.122
      p2p:
        - Ethernet1
        - Ethernet6